### ISSUE TITLE
Get new icons for split & unified diff in view/edit YAML

### ISSUE THREAD

**Issue by tfiduccia** [rancherlabs/dashboard#101]
Steps:
1. Create any type of resource
2. From the resource's menu select View/Edit YAML
3. Change something and click on Preview

Results:  The icons for split & unified diff aren't very good?  Can we get new ones?
![image](https://user-images.githubusercontent.com/11514927/68808668-78e53580-0627-11ea-98be-a2dc11925bfd.png)

**Comment by lvuch** [comment]
I think it'd be more clear if we just use text like github: <img width="213" alt="Screen Shot 2019-11-15 at 6 56 45 PM" src="https://user-images.githubusercontent.com/3013118/68986138-bbe70a80-07d9-11ea-9ad0-9b2c3807eb4d.png">

**Comment by tfiduccia** [comment]
Date - 11/18
Verified fixed
