### ISSUE TITLE
Need ability to create namespace

### ISSUE THREAD

**Issue by tfiduccia** [rancherlabs/dashboard#104]
Comments:  
Can we add the "create new namespace" in the Add Service (and other resources).  Currently there is no way to do that.

**Comment by vincent99** [comment]
Similar to Rancher, toggle between choose an existing and create a new namespace.

![image](https://user-images.githubusercontent.com/753917/68990562-e94faa80-0811-11ea-94ab-15a648383b2e.png)

![image](https://user-images.githubusercontent.com/753917/68990563-eeacf500-0811-11ea-8380-8c8077ec3c90.png)

**Comment by tfiduccia** [comment]
Date - 12/2
Verified fixed
