### ISSUE TITLE
Show confirmation prompt before delete

### ISSUE THREAD

**Issue by vincent99** [rancherlabs/dashboard#121]
On important types where deleting affects many things (e.g. namespace, stack) require confirmation by typing in the name of (one of) the important resource(s) to be removed before enabling the confirm button

(this is the`promptRemove` vs `remove` action)

**Comment by vincent99** [comment]
So all types should show the confirm modal, but only the big important types that contain many other resources (namespace & stack is good for now) should require the type-the-name confirmation

**Comment by tfiduccia** [comment]
Date - 12/2
Verified created.
