### ISSUE TITLE
General tweaks

### ISSUE THREAD

**Issue by vincent99** [rancherlabs/dashboard#42]
-  [x] Single-line (44px) LabeledInputs are not the same height as multi-line LabeledInput or LabeledSelect.  All should be something consistent.

![image](https://user-images.githubusercontent.com/753917/68188424-53d92e80-ff66-11e9-97be-8a9509322192.png)

- [x] I don't get `role-tertiary` or why it's different than choosing a background color.  If we're combing size and color into one logical role name then ok but it must be consistent throughout.  Anyway it produces buttons that have black on blue, while primary is white on blue.  One or the other is the right text color for that color of button (white).  Also the `add` variant's plus doesn't line up.

![image](https://user-images.githubusercontent.com/753917/68188522-96027000-ff66-11e9-8bdf-fbd4cd369e48.png)

![image](https://user-images.githubusercontent.com/753917/68189149-052c9400-ff68-11e9-8ac9-8eb2559538e9.png)

Icons for:
- [x] For flat vs grouped by namespace 
![image](https://user-images.githubusercontent.com/753917/68189006-b979ea80-ff67-11e9-9c75-05e775fa905d.png)

- [ ] Split vs unified YAML diff
![image](https://user-images.githubusercontent.com/753917/68189061-d44c5f00-ff67-11e9-9df4-e3d8b5ec0b72.png)

- [x] File upload
- [x] Github logo
- [x] Shell/terminal (`≥`)

**Comment by lvuch** [comment]
[icons-v1.0.zip](https://github.com/rancherlabs/dashboard/files/3848055/icons-v1.0.zip)
additional icons here

**Comment by lvuch** [comment]
I think split and unified should be text like github does

**Comment by lvuch** [comment]
unified/split fix here: https://github.com/rancherlabs/dashboard/pull/137

**Comment by tfiduccia** [comment]
Date - 11/18
Verified fixed
